// Code generated by `cmd/reset`; DO NOT EDIT.
package slices

func (gs *GenericSlices[A, B, C, D]) Reset() {
	gs.one = gs.one[:0]
	gs.two = gs.two[:0]
	gs.three = gs.three[:0]
	gs.four = gs.four[:0]
}

func (gsp *GenericSlicePointers[T]) Reset() {
	if gsp.ptr != nil {
		*gsp.ptr = (*gsp.ptr)[:0]
	}
	if gsp.PPtr != nil {
		if *gsp.PPtr != nil {
			**gsp.PPtr = (**gsp.PPtr)[:0]
		}
	}
}

func (ps *PrimitiveSlices) Reset() {
	ps._bools = ps._bools[:0]
	ps.ints = ps.ints[:0]
	ps.Strings = ps.Strings[:0]
}

func (psp *PrimitiveSlicePointers) Reset() {
	if psp.single != nil {
		*psp.single = (*psp.single)[:0]
	}
	if psp.Double != nil {
		if *psp.Double != nil {
			**psp.Double = (**psp.Double)[:0]
		}
	}
}
