//go:build ignore

package main

import (
	"bytes"
	"flag"
	"go/format"
	"html/template"
	"log"
	"os"
	"strings"
)

var targetTypes = []codeIdent{
	{Ident: "Any", Type: "any"},
	{Ident: "Bool", Type: "bool"},
	{Ident: "Int", Type: "int"},
	{Ident: "Float", Type: "float64"},
	{Ident: "Str", Type: "string"},
	{Ident: "Err", Type: "error"},
	{Ident: "Dur", Type: "time.Duration"},
	{Ident: "Time", Type: "time.Time"},
}

const codeTmpl = `// Generated by 'go generate'
// DO NOT EDIT!

package log


{{- if .Imports }}
import (
	{{- range .Imports }}
	"{{.}}"
	{{- end }}
)
{{- end }}


// Field type constants
const (
	_ FieldType = iota
	{{- range .Types }}
	FieldType{{.Ident}}
	{{- end }}
)


// Field constructors
{{- range .Types }}
func {{.Ident}}(key string, value {{.Type}}) Field {
	return Field{Key: key, Type: FieldType{{.Ident}}, Value: value}
}
{{- end }}


// EventBuilder interface
type EventBuilder interface {
	{{- range .Types }}
	{{.Ident}}(key string, value {{.Type}}) EventBuilder
	{{- end }}
	With(fields ...Field) EventBuilder
	Msg(msg string)
	Send()
}


// eventBuilder methods
{{- range .Types }}

func (e *eventBuilder) {{.Ident}}(key string, value {{.Type}}) EventBuilder {
	e.fields = append(e.fields, Field{Key: key, Type: FieldType{{.Ident}}, Value: value})
	return e
}

{{- end }}

`

type codeIdent struct {
	Ident string
	Type  string
}

type codeData struct {
	Imports []string
	Types   []codeIdent
}

type generator struct {
	t    *template.Template
	buf  bytes.Buffer
	data codeData
}

func newGenerator(tmpl string, types []codeIdent) *generator {
	return &generator{
		t:   template.Must(template.New("").Parse(tmpl)),
		buf: bytes.Buffer{},
		data: codeData{
			Imports: []string{},
			Types:   types}}
}

func (g *generator) populateImports() {
	pkgs := []string{}
	for _, t := range g.data.Types {
		tokens := strings.Split(t.Type, ".")
		n := len(tokens)
		if n > 1 {
			pkgs = append(pkgs, strings.Join(tokens[:n-1], "."))
		}
	}
	for _, pkg := range pkgs {
		g.data.Imports = append(g.data.Imports, pkg)
	}
}

func (g *generator) Run() []byte {
	g.populateImports()

	if err := g.t.Execute(&g.buf, g.data); err != nil {
		log.Fatalf("failed to render template: %v", err)
	}

	return g.buf.Bytes()
}

func formatCode(src []byte) []byte {
	out, err := format.Source(src)
	if err != nil {
		log.Println(string(src))
		log.Fatalf("failed to format generated code: %v", err)
	}
	return out
}

func writeToFile(content []byte, outPath string) {
	if err := os.WriteFile(outPath, content, 0644); err != nil {
		log.Fatalf("failed to write output to %s: %v", outPath, err)
	}
}

func getOutPath() string {
	outPath := flag.String("o", "", "output file path")
	flag.Parse()

	if *outPath == "" {
		log.Fatalf("output file path is required")
	}
	return *outPath
}

func init() {
	log.SetFlags(0)
}

func main() {
	g := newGenerator(codeTmpl, targetTypes)
	code := g.Run()
	writeToFile(formatCode(code), getOutPath())
}
