// Generated by 'go generate'
// DO NOT EDIT!

package log

import (
	"time"
)

// Field type constants
const (
	_ FieldType = iota
	FieldTypeBool
	FieldTypeInt
	FieldTypeFloat
	FieldTypeStr
	FieldTypeErr
	FieldTypeDur
	FieldTypeTime
)

// Field constructors
func Bool(key string, value bool) Field {
	return Field{Key: key, Type: FieldTypeBool, Value: value}
}
func Int(key string, value int) Field {
	return Field{Key: key, Type: FieldTypeInt, Value: value}
}
func Float(key string, value float64) Field {
	return Field{Key: key, Type: FieldTypeFloat, Value: value}
}
func Str(key string, value string) Field {
	return Field{Key: key, Type: FieldTypeStr, Value: value}
}
func Err(key string, value error) Field {
	return Field{Key: key, Type: FieldTypeErr, Value: value}
}
func Dur(key string, value time.Duration) Field {
	return Field{Key: key, Type: FieldTypeDur, Value: value}
}
func Time(key string, value time.Time) Field {
	return Field{Key: key, Type: FieldTypeTime, Value: value}
}

// EventBuilder interface
type EventBuilder interface {
	Bool(key string, value bool) EventBuilder
	Int(key string, value int) EventBuilder
	Float(key string, value float64) EventBuilder
	Str(key string, value string) EventBuilder
	Err(key string, value error) EventBuilder
	Dur(key string, value time.Duration) EventBuilder
	Time(key string, value time.Time) EventBuilder
	With(fields ...Field) EventBuilder
	Msg(msg string)
	Send()
}

// eventBuilder methods

func (e *eventBuilder) Bool(key string, value bool) EventBuilder {
	e.fields = append(e.fields, Field{Key: key, Type: FieldTypeBool, Value: value})
	return e
}

func (e *eventBuilder) Int(key string, value int) EventBuilder {
	e.fields = append(e.fields, Field{Key: key, Type: FieldTypeInt, Value: value})
	return e
}

func (e *eventBuilder) Float(key string, value float64) EventBuilder {
	e.fields = append(e.fields, Field{Key: key, Type: FieldTypeFloat, Value: value})
	return e
}

func (e *eventBuilder) Str(key string, value string) EventBuilder {
	e.fields = append(e.fields, Field{Key: key, Type: FieldTypeStr, Value: value})
	return e
}

func (e *eventBuilder) Err(key string, value error) EventBuilder {
	e.fields = append(e.fields, Field{Key: key, Type: FieldTypeErr, Value: value})
	return e
}

func (e *eventBuilder) Dur(key string, value time.Duration) EventBuilder {
	e.fields = append(e.fields, Field{Key: key, Type: FieldTypeDur, Value: value})
	return e
}

func (e *eventBuilder) Time(key string, value time.Time) EventBuilder {
	e.fields = append(e.fields, Field{Key: key, Type: FieldTypeTime, Value: value})
	return e
}
