// Code generated by `cmd/reset`; DO NOT EDIT.
package maps

func (go_ *genericOmap[K, V, S]) Reset() {
	clear(go_.One)
	clear(go_.Two)
}

func (gmp *GenericMapPointers[K, V]) Reset() {
	if gmp.p != nil {
		clear(*gmp.p)
	}
	if gmp.pp != nil {
		if *gmp.pp != nil {
			clear(**gmp.pp)
		}
	}
}

func (map_ *maybeAmaP) Reset() {
	clear(map_.one)
	clear(map_.two)
}

func (map_ *maybeAmaPpointers) Reset() {
	if map_.oneP != nil {
		clear(*map_.oneP)
	}
	if map_.twoP != nil {
		if *map_.twoP != nil {
			clear(**map_.twoP)
		}
	}
}
