// Code generated by `cmd/reset`; DO NOT EDIT.
package interfaces

func (gi *GenericInterface[A, C, R, S, M]) Reset() {
	if v, ok := interface{}(gi.a).(interface{ Reset() }); ok { // types.Interface
		v.Reset()
	}
	if v, ok := interface{}(gi.c).(interface{ Reset() }); ok { // types.Interface
		v.Reset()
	}
	if v, ok := interface{}(gi.r).(interface{ Reset() }); ok { // types.Interface
		v.Reset()
	}
	if v, ok := interface{}(gi.s).(interface{ Reset() }); ok { // types.Interface
		v.Reset()
	}
	if v, ok := interface{}(gi.m).(interface{ Reset() }); ok { // types.Interface
		v.Reset()
	}
}

func (gip *GenericInterfacePointers[A, D, S]) Reset() {
	if gip.aP != nil {
		if v, ok := interface{}(*gip.aP).(interface{ Reset() }); ok { // types.Interface (pointer)
			v.Reset()
		}
	}
	if gip.dP != nil {
		if v, ok := interface{}(*gip.dP).(interface{ Reset() }); ok { // types.Interface (pointer)
			v.Reset()
		}
	}
	if gip.ddP != nil {
		if *gip.ddP != nil {
			if v, ok := interface{}(**gip.ddP).(interface{ Reset() }); ok { // types.Interface (pointer)
				v.Reset()
			}
		}
	}
	if gip.ssP != nil {
		if *gip.ssP != nil {
			if v, ok := interface{}(**gip.ssP).(interface{ Reset() }); ok { // types.Interface (pointer)
				v.Reset()
			}
		}
	}
}

func (eiv *EmbeddedInterfaceValue) Reset() {
	if v, ok := interface{}(eiv.Resettable).(interface{ Reset() }); ok { // types.Interface
		v.Reset()
	}
	if v, ok := interface{}(eiv.Dummy).(interface{ Reset() }); ok { // types.Interface
		v.Reset()
	}
}

func (iaf *InterfaceAsField) Reset() {
	if v, ok := interface{}(iaf.f).(interface{ Reset() }); ok { // types.Interface
		v.Reset()
	}
	if iaf.fp != nil {
		if v, ok := interface{}(*iaf.fp).(interface{ Reset() }); ok { // types.Interface (pointer)
			v.Reset()
		}
	}
}
