//go:build ignore

package main

import (
	"bytes"
	"context"
	"flag"
	"go/format"
	"log"
	"os"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

type codeData struct {
	Imports   []string
	Analyzers []string
}

const parentPackage = "golang.org/x/tools/go/analysis/passes"

const codeTmpl = `// Code generated by 'go generate'. DO NOT EDIT.
package passes

import (
	"golang.org/x/tools/go/analysis"

	{{- range .Imports }}
	"{{.}}"
	{{- end}}
)

var Analyzers = [{{len .Analyzers}}]*analysis.Analyzer{
	{{- range .Analyzers }}
	{{.}}.Analyzer,
	{{- end}}
}
`

type cliOpts struct {
	OutPath           string
	ExcludedAnalyzers map[string]bool
}

func main() {
	opts := parseArgs()

	generateCode(opts.OutPath, opts.ExcludedAnalyzers)
}

func parseArgs() cliOpts {
	var (
		opts    cliOpts
		exclude string
	)

	flag.StringVar(&opts.OutPath, "o", "", "output file path (required)")
	flag.StringVar(&exclude, "exclude", "", "comma-separated list of excluded analyzers (e.g. fieldalignment,loopclosure)")

	flag.Parse()

	if opts.OutPath == "" {
		log.Fatal("output file path is required (use -o PATH)")
	}

	opts.ExcludedAnalyzers = make(map[string]bool)
	for _, name := range strings.Split(exclude, ",") {
		opts.ExcludedAnalyzers[name] = true
	}

	return opts
}

func generateCode(outPath string, excludedAnalyzers map[string]bool) {
	ctx := context.Background()

	cfg := &packages.Config{
		Context: ctx,
		Mode:    packages.LoadTypes,
	}

	pkgs, err := packages.Load(cfg, parentPackage+"/...")
	if err != nil {
		log.Fatalf("cannot load packages from %s: %v", parentPackage, err)
	}

	data := populateCodeData(pkgs, excludedAnalyzers)

	content := renderTemplate(data)

	err = os.WriteFile(outPath, content, 0o644)
	if err != nil {
		log.Fatalf("cannot write generated code to %s: %v", outPath, err)
	}
}

func renderTemplate(data codeData) []byte {
	tmpl := template.Must(template.New("").Parse(codeTmpl))

	buf := bytes.NewBuffer(nil)

	err := tmpl.Execute(buf, data)
	if err != nil {
		log.Fatalf("cannot render template: %v", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Println(buf.String())
		log.Fatalf("failed to format generated code (printed above): %v", err)
	}

	return formatted
}

func populateCodeData(pkgs []*packages.Package, excludedAnalyzers map[string]bool) codeData {
	var data codeData

	for _, pkg := range pkgs {
		if pkg.Name == "main" {
			// skip CLI tools
			continue
		}

		if strings.Contains(pkg.PkgPath, "/internal/") {
			// skip internal packages
			continue
		}

		if excludedAnalyzers[pkg.Name] {
			// skip excluded analyzers
			continue
		}

		data.Imports = append(data.Imports, pkg.PkgPath)
		data.Analyzers = append(data.Analyzers, pkg.Name)
	}

	return data
}
