package passes

// Package passes contains a list of all analyzers from `golang.org/x/tools/go/analysis/passes`.
// The list is generated by inspecting `golang.org/x/tools/go/analysis/passes` with `golang.org/x/tools/go/packages`.

// FIXME: fieldalignment generates a lot of noise, so excluding it for now.
//go:generate go run ./generate.go -o passes_gen.go -exclude=fieldalignment
