package passes

// Package passes contains a list of all analyzers from `golang.org/x/tools/go/analysis/passes`.
// The list is generated by inspecting `golang.org/x/tools/go/analysis/passes` with `golang.org/x/tools/go/packages`.

// Excluded:
// - `fieldalignment` generates a lot of noise on current codebase, excluding for now.
// - `modernize` is a special analyzer, not strictly required.
//
//go:generate go run ./generate.go -o passes_gen.go -exclude=fieldalignment,modernize
