// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-metrics/pkg/retrymgr (interfaces: Strategy)
//
// Generated by this command:
//
//	mockgen -destination=retrymgrtest/mock_strategy.go -package retrymgrtest github.com/bq2cd/yp-go-metrics/pkg/retrymgr Strategy
//

// Package retrymgrtest is a generated GoMock package.
package retrymgrtest

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStrategy is a mock of Strategy interface.
type MockStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyMockRecorder
	isgomock struct{}
}

// MockStrategyMockRecorder is the mock recorder for MockStrategy.
type MockStrategyMockRecorder struct {
	mock *MockStrategy
}

// NewMockStrategy creates a new mock instance.
func NewMockStrategy(ctrl *gomock.Controller) *MockStrategy {
	mock := &MockStrategy{ctrl: ctrl}
	mock.recorder = &MockStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategy) EXPECT() *MockStrategyMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockStrategy) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockStrategyMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockStrategy)(nil).Name))
}

// NextDelay mocks base method.
func (m *MockStrategy) NextDelay() (time.Duration, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextDelay")
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// NextDelay indicates an expected call of NextDelay.
func (mr *MockStrategyMockRecorder) NextDelay() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextDelay", reflect.TypeOf((*MockStrategy)(nil).NextDelay))
}
