// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-metrics/internal/app/agent/source (interfaces: Source)
//
// Generated by this command:
//
//	mockgen -destination=sourcetest/mock_source.go -package sourcetest github.com/bq2cd/yp-go-metrics/internal/app/agent/source Source
//

// Package sourcetest is a generated GoMock package.
package sourcetest

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	model "github.com/bq2cd/yp-go-metrics/internal/model"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
	isgomock struct{}
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// ReadMetrics mocks base method.
func (m *MockSource) ReadMetrics() ([]model.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMetrics")
	ret0, _ := ret[0].([]model.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadMetrics indicates an expected call of ReadMetrics.
func (mr *MockSourceMockRecorder) ReadMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMetrics", reflect.TypeOf((*MockSource)(nil).ReadMetrics))
}
