// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-metrics/internal/repository (interfaces: AuditSink)
//
// Generated by this command:
//
//	mockgen -destination=auditsink/auditsinktest/mock_audit_sink.go -package auditsinktest github.com/bq2cd/yp-go-metrics/internal/repository AuditSink
//

// Package auditsinktest is a generated GoMock package.
package auditsinktest

import (
	context "context"
	reflect "reflect"

	model "github.com/bq2cd/yp-go-metrics/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditSink is a mock of AuditSink interface.
type MockAuditSink struct {
	ctrl     *gomock.Controller
	recorder *MockAuditSinkMockRecorder
	isgomock struct{}
}

// MockAuditSinkMockRecorder is the mock recorder for MockAuditSink.
type MockAuditSinkMockRecorder struct {
	mock *MockAuditSink
}

// NewMockAuditSink creates a new mock instance.
func NewMockAuditSink(ctrl *gomock.Controller) *MockAuditSink {
	mock := &MockAuditSink{ctrl: ctrl}
	mock.recorder = &MockAuditSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditSink) EXPECT() *MockAuditSinkMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAuditSink) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAuditSinkMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAuditSink)(nil).Close))
}

// WriteEvent mocks base method.
func (m *MockAuditSink) WriteEvent(ctx context.Context, event model.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteEvent indicates an expected call of WriteEvent.
func (mr *MockAuditSinkMockRecorder) WriteEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteEvent", reflect.TypeOf((*MockAuditSink)(nil).WriteEvent), ctx, event)
}
