package osexit

import (
	"go/token"
	"strings"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/buildssa"
	"golang.org/x/tools/go/callgraph/rta"
	"golang.org/x/tools/go/ssa"
)

type checker struct {
	pass *analysis.Pass
	ssa  *buildssa.SSA
}

func newChecker(pass *analysis.Pass) (*checker, error) {
	ssa, ok := pass.ResultOf[buildssa.Analyzer].(*buildssa.SSA)
	if !ok {
		return nil, ErrMissingRequiredAnalyzers
	}

	c := &checker{
		pass: pass,
		ssa:  ssa,
	}

	return c, nil
}

// Run analyzes a call graph of the inspected function and reports all top-level calls
// that eventually reach forbidden function.
// The call graph is constructed using `RTA` (Rapid Type Analysis) method as implemented in
// `golang.org/x/tools/go/callgraph/rta` package (see its documentation on implementation details).
// Since the constructed graph may include calls that are never executed or miss some dynamic calls (e.g.
// via reflection), the analyzer might produce both false positive and false negative results.
// The algorithm works as follows:
//   - a call graph is constructed from the results of `golang.org/x/tools/go/analysis/passes/buildssa` pass.
//   - the call graph is traversed to find all reachable functions starting from the inspected function.
//   - if the reachable functions do not contain the forbidden function, the algorithm terminates.
//   - a reverse traversal of the call graph is performed, starting from the forbidden function, until
//     all "roots" ("root" - starting point of the call chain that ends with the forbidden function) are found.
//   - for any "root" that belongs to the inspected function, a violation is reported.
func (c *checker) Run() error {
	if !c.needPackageInspection() {
		return nil
	}

	inspected := c.loadInspectedFunction()
	if inspected == nil {
		// inspected function is not found in the inspected package
		return nil
	}

	forbidden := c.loadForbiddenFunction()
	if forbidden == nil {
		// forbidden function is not imported by the inspected package
		return nil
	}

	c.detectForbiddenCalls(inspected, forbidden)

	return nil
}

func (c *checker) needPackageInspection() bool {
	// hacky way to ignore test packages (generated by Go compiler if there are `_test.go` files).
	if strings.HasSuffix(c.pass.Pkg.Path(), ".test") {
		return false
	}

	return c.pass.Pkg.Name() == inspectedPackage
}

func (c *checker) loadInspectedFunction() *ssa.Function {
	member, ok := c.ssa.Pkg.Members[inspectedFunction]
	if !ok {
		return nil
	}

	fn, ok := member.(*ssa.Function)
	if !ok {
		return nil
	}

	pos := c.pass.Fset.Position(fn.Pos())

	// hacky way to ignore functions in generated files (e.g. main function generated for `_test.go` files).
	if !strings.HasSuffix(pos.Filename, ".go") {
		return nil
	}

	return fn
}

func (c *checker) loadForbiddenFunction() *ssa.Function {
	pkg := c.ssa.Pkg.Prog.ImportedPackage(forbiddenPackage)
	if pkg == nil {
		return nil
	}

	return pkg.Func(forbiddenFunction)

}

func (c *checker) detectForbiddenCalls(inspected, forbidden *ssa.Function) {
	result := rta.Analyze([]*ssa.Function{inspected}, true)

	reachable := findReachableFunctions(result.CallGraph, inspected)
	if !reachable[forbidden] {
		return
	}

	roots := findFunctionRoots(result.CallGraph, forbidden)

	for _, call := range roots[inspected] {
		c.reportViolation(call.Pos())
	}
}

func (c *checker) reportViolation(pos token.Pos) {
	c.pass.Reportf(pos, "%s.%s is not allowed in %s function", forbiddenPackage, forbiddenFunction, inspectedFunction)
}
