// Code generated by `cmd/reset`; DO NOT EDIT.
package structs

func (ev *EmbeddedValue) Reset() {
	if v, ok := interface{}(&ev.Standalone).(interface{ Reset() }); ok { // types.Struct
		v.Reset()
	}
	ev.V = 0
}

func (ep *EmbeddedPointer) Reset() {
	if ep.Standalone != nil {
		if v, ok := interface{}(ep.Standalone).(interface{ Reset() }); ok { // types.Struct (pointer)
			v.Reset()
		}
	}
	ep.V = 0
}

func (esaf_ *ExternalStructAsField) Reset() {
	if esaf_.buf != nil {
		if v, ok := interface{}(esaf_.buf).(interface{ Reset() }); ok { // types.Struct (pointer)
			v.Reset()
		}
	}
	if esaf_.bufP != nil {
		if *esaf_.bufP != nil {
			if v, ok := interface{}(*esaf_.bufP).(interface{ Reset() }); ok { // types.Struct (pointer)
				v.Reset()
			}
		}
	}
}

func (saf *StructAsField) Reset() {
	if v, ok := interface{}(&saf.ref).(interface{ Reset() }); ok { // types.Struct
		v.Reset()
	}
	if v, ok := interface{}(&saf.S).(interface{ Reset() }); ok { // types.Struct
		v.Reset()
	}
	if saf.SP != nil {
		if v, ok := interface{}(saf.SP).(interface{ Reset() }); ok { // types.Struct (pointer)
			v.Reset()
		}
	}
	if saf.SPP != nil {
		if *saf.SPP != nil {
			if v, ok := interface{}(*saf.SPP).(interface{ Reset() }); ok { // types.Struct (pointer)
				v.Reset()
			}
		}
	}
}

func (sr *SelfReferential) Reset() {
	if sr.left != nil {
		if v, ok := interface{}(sr.left).(interface{ Reset() }); ok { // types.Struct (pointer)
			v.Reset()
		}
	}
	if sr.parent != nil {
		if *sr.parent != nil {
			if v, ok := interface{}(*sr.parent).(interface{ Reset() }); ok { // types.Struct (pointer)
				v.Reset()
			}
		}
	}
}
