// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-metrics/pkg/hmacsigner (interfaces: HMACSigner)
//
// Generated by this command:
//
//	mockgen -destination=hmacsignertest/mock_hmacsigner.go -package hmacsignertest github.com/bq2cd/yp-go-metrics/pkg/hmacsigner HMACSigner
//

// Package hmacsignertest is a generated GoMock package.
package hmacsignertest

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHMACSigner is a mock of HMACSigner interface.
type MockHMACSigner struct {
	ctrl     *gomock.Controller
	recorder *MockHMACSignerMockRecorder
	isgomock struct{}
}

// MockHMACSignerMockRecorder is the mock recorder for MockHMACSigner.
type MockHMACSignerMockRecorder struct {
	mock *MockHMACSigner
}

// NewMockHMACSigner creates a new mock instance.
func NewMockHMACSigner(ctrl *gomock.Controller) *MockHMACSigner {
	mock := &MockHMACSigner{ctrl: ctrl}
	mock.recorder = &MockHMACSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHMACSigner) EXPECT() *MockHMACSignerMockRecorder {
	return m.recorder
}

// HasKey mocks base method.
func (m *MockHMACSigner) HasKey() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasKey")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasKey indicates an expected call of HasKey.
func (mr *MockHMACSignerMockRecorder) HasKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasKey", reflect.TypeOf((*MockHMACSigner)(nil).HasKey))
}

// Sign mocks base method.
func (m *MockHMACSigner) Sign(signingMessage []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", signingMessage)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign.
func (mr *MockHMACSignerMockRecorder) Sign(signingMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockHMACSigner)(nil).Sign), signingMessage)
}

// Verify mocks base method.
func (m *MockHMACSigner) Verify(signedMessage, signature []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", signedMessage, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockHMACSignerMockRecorder) Verify(signedMessage, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockHMACSigner)(nil).Verify), signedMessage, signature)
}
