// Code generated by `cmd/reset`; DO NOT EDIT.
package primitives

func (bv *BoolValues) Reset() {
	bv.a = false
	bv.B = false
}

func (bp *BoolPointers) Reset() {
	if bp.p != nil {
		*bp.p = false
	}
}

func (fv *Float64Values) Reset() {
	fv.a = 0.0
	fv.B = 0.0
}

func (for_ *Float64ORpointers) Reset() {
	if for_.P != nil {
		if *for_.P != nil {
			**for_.P = 0.0
		}
	}
}

func (fv *Float32Values) Reset() {
	fv.A = 0.0
}

func (fp *Float32Pointers) Reset() {
	if fp.p != nil {
		*fp.p = 0.0
	}
}

func (if_ *IntFramework) Reset() {
	if_.a = 0
	if_.b = 0
	if_.c = 0
	if_.V64 = 0
	if_.V32 = 0
	if_.V16 = 0
	if_.V8 = 0
}

func (uif *unsignedIntFramework) Reset() {
	uif.a = 0
	uif.b = 0
	uif.c = 0
	uif.V64 = 0
	uif.V32 = 0
	uif.V16 = 0
	uif.V8 = 0
}

func (ip *IntPointers) Reset() {
	if ip.A != nil {
		*ip.A = 0
	}
	if ip.B != nil {
		if *ip.B != nil {
			**ip.B = 0
		}
	}
	if ip.C != nil {
		if *ip.C != nil {
			if **ip.C != nil {
				***ip.C = 0
			}
		}
	}
}

func (svap_ *StringValuesAndPointers) Reset() {
	svap_.s = ""
	svap_.S = ""
	if svap_.p != nil {
		*svap_.p = ""
	}
	if svap_.P != nil {
		*svap_.P = ""
	}
	if svap_.PP != nil {
		if *svap_.PP != nil {
			**svap_.PP = ""
		}
	}
}
