// Code generated by `cmd/reset`; DO NOT EDIT.
package magiccommentdetection

func (sa *StructA) Reset() {
	sa.a = 0
}

func (sb *StructB) Reset() {
	sb.B = 0
}

func (sma *StructMultiA) Reset() {
	sma.a = 0
}

func (smb *StructMultiB) Reset() {
	smb.B = 0
}

func (smc *StructMultiC) Reset() {
	smc.c = 0
}

func (smd *StructMultiD) Reset() {
	smd.D = 0
}

func (gsa *GroupStructA) Reset() {
	gsa.A = 0
}

func (gsc *GroupStructC) Reset() {
	gsc.C = 0
}

func (gsd *GroupStructD) Reset() {
	gsd.D = 0
}

func (gse *GroupStructE) Reset() {
	gse.E = 0
}
