// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-metrics/internal/service (interfaces: MetricAuditor)
//
// Generated by this command:
//
//	mockgen -destination=servicetest/mock_metric_auditor.go -package servicetest github.com/bq2cd/yp-go-metrics/internal/service MetricAuditor
//

// Package servicetest is a generated GoMock package.
package servicetest

import (
	context "context"
	reflect "reflect"

	model "github.com/bq2cd/yp-go-metrics/internal/model"
	repository "github.com/bq2cd/yp-go-metrics/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricAuditor is a mock of MetricAuditor interface.
type MockMetricAuditor struct {
	ctrl     *gomock.Controller
	recorder *MockMetricAuditorMockRecorder
	isgomock struct{}
}

// MockMetricAuditorMockRecorder is the mock recorder for MockMetricAuditor.
type MockMetricAuditorMockRecorder struct {
	mock *MockMetricAuditor
}

// NewMockMetricAuditor creates a new mock instance.
func NewMockMetricAuditor(ctrl *gomock.Controller) *MockMetricAuditor {
	mock := &MockMetricAuditor{ctrl: ctrl}
	mock.recorder = &MockMetricAuditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricAuditor) EXPECT() *MockMetricAuditorMockRecorder {
	return m.recorder
}

// RecordMetricsUploaded mocks base method.
func (m *MockMetricAuditor) RecordMetricsUploaded(ctx context.Context, metrics model.MetricSet, clientInfo model.ClientInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordMetricsUploaded", ctx, metrics, clientInfo)
}

// RecordMetricsUploaded indicates an expected call of RecordMetricsUploaded.
func (mr *MockMetricAuditorMockRecorder) RecordMetricsUploaded(ctx, metrics, clientInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordMetricsUploaded", reflect.TypeOf((*MockMetricAuditor)(nil).RecordMetricsUploaded), ctx, metrics, clientInfo)
}

// RegisterSink mocks base method.
func (m *MockMetricAuditor) RegisterSink(sink repository.AuditSink) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterSink", sink)
}

// RegisterSink indicates an expected call of RegisterSink.
func (mr *MockMetricAuditorMockRecorder) RegisterSink(sink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterSink", reflect.TypeOf((*MockMetricAuditor)(nil).RegisterSink), sink)
}
