// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bq2cd/yp-go-metrics/internal/service (interfaces: StoragePinger)
//
// Generated by this command:
//
//	mockgen -destination=servicetest/mock_storage_pinger.go -package servicetest github.com/bq2cd/yp-go-metrics/internal/service StoragePinger
//

// Package servicetest is a generated GoMock package.
package servicetest

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStoragePinger is a mock of StoragePinger interface.
type MockStoragePinger struct {
	ctrl     *gomock.Controller
	recorder *MockStoragePingerMockRecorder
	isgomock struct{}
}

// MockStoragePingerMockRecorder is the mock recorder for MockStoragePinger.
type MockStoragePingerMockRecorder struct {
	mock *MockStoragePinger
}

// NewMockStoragePinger creates a new mock instance.
func NewMockStoragePinger(ctrl *gomock.Controller) *MockStoragePinger {
	mock := &MockStoragePinger{ctrl: ctrl}
	mock.recorder = &MockStoragePingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoragePinger) EXPECT() *MockStoragePingerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockStoragePinger) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStoragePingerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStoragePinger)(nil).Ping), ctx)
}
